/* GENERATED by tools/gen_web_assets.py — do not edit. */
#pragma once
#include <stddef.h>

extern const char index_html[];
extern const size_t index_html_len;
extern const char wifi_setup_html[];
extern const size_t wifi_setup_html_len;
extern const char cal_upload_html[];
extern const size_t cal_upload_html_len;
extern const char files_html[];
extern const size_t files_html_len;
extern const char settings_html[];
extern const size_t settings_html_len;
extern const char style_css[];
extern const size_t style_css_len;
extern const char app_js[];
extern const size_t app_js_len;
