#!/usr/bin/env python3
"""Convert the wordmark into a compiled-in LVGL image for the boot splash.

No image decoder is built into this LVGL configuration (LV_USE_LODEPNG,
LV_USE_BMP and LV_USE_TJPGD are all off) and LV_COLOR_DEPTH is 16, so the
splash logo has to be a raw RGB565 C array rather than a PNG on the SD card.
The upstream converter (managed_components/lvgl__lvgl/scripts/LVGLImage.py)
needs Pillow, which is not installed in any interpreter here — ImageMagick
does the decode and resize instead and this script packs the pixels.

Run after changing the source artwork, then rebuild:

    python3 tools/gen_splash_logo.py
"""
import pathlib
import subprocess

ROOT  = pathlib.Path(__file__).resolve().parent.parent
SRC   = ROOT / "Docu/images/SpectraLab-P4-splash.png"
OUT_C = ROOT / "components/display_ui/src/splash_logo.c"
OUT_H = ROOT / "components/display_ui/src/splash_logo.h"
WIDTH = 760          # of a 1024 px panel, leaving room for the credit + spinner

# -depth 8 RGB: gives packed 8-bit R,G,B triples on stdout, no header.
size = subprocess.run(["magick", str(SRC), "-resize", f"{WIDTH}x",
                       "-format", "%w %h", "info:"],
                      check=True, capture_output=True, text=True).stdout.split()
w, h = int(size[0]), int(size[1])
rgb = subprocess.run(["magick", str(SRC), "-resize", f"{WIDTH}x",
                      "-depth", "8", "RGB:-"],
                     check=True, capture_output=True).stdout
assert len(rgb) == w * h * 3, f"expected {w * h * 3} bytes, got {len(rgb)}"

# RGB565, little-endian — the byte order LVGL reads for LV_COLOR_FORMAT_RGB565.
px = bytearray(w * h * 2)
for i in range(w * h):
    r, g, b = rgb[i * 3], rgb[i * 3 + 1], rgb[i * 3 + 2]
    v = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
    px[i * 2]     = v & 0xFF
    px[i * 2 + 1] = v >> 8

body = []
for i in range(0, len(px), 16):
    body.append("    " + ", ".join(f"0x{b:02x}" for b in px[i:i + 16]) + ",")

OUT_H.write_text(f"""/* GENERATED by tools/gen_splash_logo.py — do not edit. */
#pragma once
#include "lvgl.h"

/* {w}x{h} RGB565 wordmark shown by the boot splash. */
extern const lv_image_dsc_t splash_logo;
""")

OUT_C.write_text(f"""/* GENERATED by tools/gen_splash_logo.py — do not edit. */
#include "splash_logo.h"

static const uint8_t splash_logo_map[] = {{
{chr(10).join(body)}
}};

const lv_image_dsc_t splash_logo = {{
    .header = {{
        .magic  = LV_IMAGE_HEADER_MAGIC,
        .cf     = LV_COLOR_FORMAT_RGB565,
        .w      = {w},
        .h      = {h},
        .stride = {w * 2},
    }},
    .data_size = sizeof(splash_logo_map),
    .data      = splash_logo_map,
}};
""")
print(f"wrote {OUT_C.name} ({w}x{h}, {len(px)} bytes of pixels) + {OUT_H.name}")
