#!/usr/bin/env python3
"""Convert the web/ assets into C arrays (components/web_server/src/web_assets.c/.h).

PlatformIO's SCons wrapper mishandles ESP-IDF's EMBED_TXTFILES (the generated
.S file is looked up in the wrong build directory), so the assets are baked
into checked-in C sources instead. Re-run this script after editing web/*:

    python3 tools/gen_web_assets.py
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
ASSETS = [
    ("index_html",      ROOT / "web/index.html"),
    ("wifi_setup_html", ROOT / "web/wifi-setup.html"),
    ("cal_upload_html", ROOT / "web/cal-upload.html"),
    ("files_html",      ROOT / "web/files.html"),
    ("settings_html",   ROOT / "web/settings.html"),
    ("style_css",       ROOT / "web/style.css"),
    ("app_js",          ROOT / "web/app.js"),
    # Binary is fine here — the bytes are emitted raw and _len is exact.
    # Regenerate this one with tools/gen_brand_icon.py first.
    ("favicon_png",     ROOT / "web/favicon.png"),
]
OUT_C = ROOT / "components/web_server/src/web_assets.c"
OUT_H = ROOT / "components/web_server/src/web_assets.h"

h = ["/* GENERATED by tools/gen_web_assets.py — do not edit. */",
     "#pragma once", "#include <stddef.h>", ""]
c = ["/* GENERATED by tools/gen_web_assets.py — do not edit. */",
     '#include "web_assets.h"', ""]

for name, path in ASSETS:
    data = path.read_bytes()
    h.append(f"extern const char {name}[];")
    h.append(f"extern const size_t {name}_len;")
    lines = [f"const char {name}[] = {{"]
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i+16])
        lines.append(f"    {chunk},")
    lines.append("    0x00};")   # NUL-terminated for convenience
    lines.append(f"const size_t {name}_len = {len(data)};")
    lines.append("")
    c.extend(lines)

OUT_H.write_text("\n".join(h) + "\n")
OUT_C.write_text("\n".join(c) + "\n")
print(f"wrote {OUT_C.name} ({OUT_C.stat().st_size} bytes) + {OUT_H.name}")
